### ISSUE TITLE
Improve ArrayControl

### ISSUE THREAD

**Issue by nikgraf** [pure-ui/styleguide#42]
Allow to add an entry at the end. -> big plus icon
All to remove an entry from the end. -> big minus icon next to the plus

**Comment by busypeoples** [comment]
Check the reference implementation.
https://github.com/busypeoples/styleguide/blob/improve_array_control/plugin/default-plugins/playground/frontend/components/controls/ArrayControl/index.js#L20

The problem here is that you might or might not receive an according to the required propTypeData. This also means that you might click on the plus icon and not receive a new entry.

**Comment by nikgraf** [comment]
@busypeoples In this case you could extend the propType data with required: true. We fixed that last night. There should be no second argument for randomValue.
